language: cpp

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc
      addons:
        apt:
          packages:
            - libvtk6-dev
            - ocl-icd-opencl-dev
            - libgtk2.0-dev
            - libwxgtk3.0-dev
    - os: osx
      osx_image: xcode7.3
      compiler: clang
      before_install:
        - brew update
        - brew install homebrew/science/vtk wxmac

branches:
  only:
    - gh-pages

before_script:  
    - mkdir build
    - cd build
    - cmake ..

script: make 
