language: cpp

matrix:
  include:
    - os: windows
      name: Windows_vtk8.1.2_wx3.1.3
      before_install:
        # Build Boost (just program_options, for speed)
        - wget -q -O boost_1_64_0.tar.gz http://sourceforge.net/projects/boost/files/boost/1.64.0/boost_1_64_0.tar.gz/download
        - tar xzf boost_1_64_0.tar.gz > NUL
        - cd boost_1_64_0/
        - ./bootstrap.sh -with-libraries=program_options
        - ./b2 -j8 toolset=msvc-14.1 address-model=32 architecture=x86 link=static threading=multi runtime-link=static release --build-type=complete -a -d0
        - cd ..
        - BOOST_ROOT=-DBOOST_ROOT:PATH=$PWD/boost_1_64_0
        # Install OpenCL SDK
        - NUGETDIR="C:/NUGET"
        - choco install nuget.commandline
        - nuget install opencl-nug -Version 0.777.77 -OutputDirectory $NUGETDIR
        - OCL_ROOT="$NUGETDIR/opencl-nug.0.777.77/build/native"
        - OCL_INCLUDE=-DOPENCL_INCLUDE_DIRS:PATH=$OCL_ROOT/include
        - OCL_LIB=-DOPENCL_LIBRARIES:PATH=$OCL_ROOT/lib/x86/OpenCL.lib
        # Set up msbuild
        - MSBUILD_PATH="/C/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin"
        - export PATH=$PATH:$MSBUILD_PATH
        # Build wxWidgets
        - wget -q https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.3/wxWidgets-3.1.3.tar.bz2
        - tar xf wxWidgets-3.1.3.tar.bz2 > NUL
        - set _CL_=/MT
        - MSBuild.exe -p:Configuration=Release -m -v:quiet wxWidgets-3.1.3/build/msw/wx_vc14.sln
        - WX_ROOT_HINT=-DwxWidgets_ROOT_DIR:PATH=$PWD/wxWidgets-3.1.3/
        - WX_LIB_HINT=-DwxWidgets_LIB_DIR:PATH=$PWD/wxWidgets-3.1.3/lib/vc_lib
        # Install VTK binaries
        - wget -q https://github.com/GollyGang/ready/releases/download/0.8/VTK-8.1.2_msvc14_x86_shared.7z
        - 7z x VTK-8.1.2_msvc14_x86_shared.7z
        - VTK_HINT=-DVTK_DIR=$PWD/VTK/lib/cmake/vtk-8.1
    - os: linux
      name: Ubuntu_18.04_gtk3_vtk7_wx3.0.4
      dist: bionic
      compiler: gcc
      addons:
        apt:
          packages:
            - libvtk7-dev
            - ocl-icd-opencl-dev
            - libgtk-3-dev
            - libwxgtk3.0-gtk3-dev
            - libboost-program-options-dev
    - os: linux
      name: Ubuntu_16.04_gtk2_vtk6_wx3.0.2
      dist: xenial
      compiler: gcc
      addons:
        apt:
          packages:
            - libvtk6-dev
            - ocl-icd-opencl-dev
            - libgtk2.0-dev
            - libwxgtk3.0-dev
            - libboost-program-options-dev
    - os: osx
      osx_image: xcode11.3
      name: MacOS_10.14_xcode11.3_vtk8.2.0_wx3.0.4
      addons:
        homebrew:
          packages:
            - vtk
            - wxmac
            - boost
    - os: osx
      name: MacOS_10.13_xcode9.4.1_vtk8.2.0_wx3.0.4
      addons:
        homebrew:
          packages:
            - vtk
            - wxmac
            - boost

branches:
  only:
    - gh-pages

before_script:  
    - mkdir build
    - cd build
    - cmake $VTK_HINT $WX_ROOT_HINT $WX_LIB_HINT $OCL_INCLUDE $OCL_LIB $BOOST_ROOT -DCMAKE_BUILD_TYPE=Release ..

script: cmake --build . --config Release
