sudo: required
dist: trusty

branches:
  only:
    - gh-pages

addons:
  apt:
    packages:
    - libvtk6-dev
    - ocl-icd-opencl-dev
    - libgtk2.0-dev
    - libwxgtk3.0-dev

language: cpp

compiler:  
    - gcc

before_script:  
    - mkdir build
    - cd build
    - cmake ..

script: make 
