language: cpp

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc
      addons:
        apt:
          packages:
            - libvtk6-dev
            - ocl-icd-opencl-dev
            - libgtk2.0-dev
            - libwxgtk3.0-dev
            - libboost-all-dev
    - os: osx
      before_install:
        - brew update
        - brew install vtk wxmac boost
    - os: windows
      before_install:
        - choco install wxwidgets

branches:
  only:
    - gh-pages

before_script:  
    - mkdir build
    - cd build
    - cmake ..

script: make 
