language: cpp

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc
      addons:
        apt:
          packages:
            - libvtk6-dev
            - ocl-icd-opencl-dev
            - libgtk2.0-dev
            - libwxgtk3.0-dev
            - libboost-all-dev
    - os: osx
      before_install:
        - brew install vtk wxmac boost
  allow_failures:
    - os: windows
      before_install:
        - choco install wxwidgets boost-msvc-12
        - pushd .
        - wget https://www.vtk.org/files/release/8.1/VTK-8.1.2.zip
        - 7z x VTK-8.1.2.zip
        - mkdir VTK_build
        - cd VTK_build
        - cmake ../VTK-8.1.2
        - cmake --build .
        - CMAKE_HINTS=-DVTK_DIR=$PWD
        - popd

branches:
  only:
    - gh-pages

before_script:  
    - mkdir build
    - cd build
    - cmake $CMAKE_HINTS ..

script: make 
