language: cpp

matrix:
  include:
    - os: linux
      sudo: required
      dist: bionic
      compiler: gcc
      addons:
        apt:
          packages:
            - libvtk7-dev
            - ocl-icd-opencl-dev
            - libgtk-3-dev
            - libwxgtk3.0-gtk3-dev
            - libboost-all-dev
    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc
      addons:
        apt:
          packages:
            - libvtk6-dev
            - ocl-icd-opencl-dev
            - libgtk2.0-dev
            - libwxgtk3.0-dev
            - libboost-all-dev
    - os: osx
      before_install:
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install vtk wxmac boost
    - os: windows
      before_install:
        - choco install boost-msvc-12 opencl-intel-cpu-runtime wxwidgets
        - wget https://github.com/GollyGang/ready/releases/download/0.8/VTK-8.1.2_msvc14_x86_shared.7z
        - 7z x VTK-8.1.2_msvc14_x86_shared.7z
        - VTK_HINT=-DVTK_DIR=$PWD/VTK/lib/cmake/vtk-8.1

branches:
  only:
    - gh-pages

before_script:  
    - mkdir build
    - cd build
    - cmake $VTK_HINT $WX_LIB_HINT ..

script: make 
