language: cpp

matrix:
  include:
    - os: windows
      name: Windows_vtk8.1.2_wx3.1.3
      before_install:
        # Build Boost (just program_options, for speed)
        - wget -q -O boost_1_64_0.tar.gz http://sourceforge.net/projects/boost/files/boost/1.64.0/boost_1_64_0.tar.gz/download
        - tar xzf boost_1_64_0.tar.gz > NUL
        - cd boost_1_64_0/
        - ./bootstrap.sh -with-libraries=program_options
        - ./b2 -j8 toolset=msvc-14.1 address-model=32 architecture=x86 link=static threading=multi runtime-link=static release --build-type=complete -a -d0
        - cd ..
        - BOOST_ROOT=-DBOOST_ROOT:PATH=$PWD/boost_1_64_0
        # Install OpenCL SDK
        - NUGETDIR="C:/NUGET"
        - choco install nuget.commandline
        - nuget install opencl-nug -Version 0.777.77 -OutputDirectory $NUGETDIR
        - OCL_ROOT="$NUGETDIR/opencl-nug.0.777.77/build/native"
        - OCL_INCLUDE=-DOPENCL_INCLUDE_DIRS:PATH=$OCL_ROOT/include
        - OCL_LIB=-DOPENCL_LIBRARIES:PATH=$OCL_ROOT/lib/x86/OpenCL.lib
        - export PATH=$OCL_ROOT/bin:$PATH
        # Set up nmake in order to build wxWidgets
        - export VSVER=2017
        - export MSVER=14.16.27023
        - export SDKVER=10.0.17763.0
        - export FRAMEVER=4.0.30319
        - export NETFXVER=4.6.1
        - export WKITVER=10.0.17134.0
        - export TOOLSVER=BuildTools
        - export PATH=/c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/$VSVER/$TOOLSVER/Common7/IDE/VC/VCPackages:$PATH
        - export PATH=/c/Program\ Files\ \(x86\)/Windows\ Kits/10/bin/$WKITVER/x64:$PATH
        - export PATH=/c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/$VSVER/$TOOLSVER/VC/Tools/MSVC/$MSVER/bin/HostX64/x64:$PATH
        - export PATH=/c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/$VSVER/$TOOLSVER/VC/Tools/MSVC/$MSVER/bin/HostX64/x86:$PATH
        - export PATH=$PATH:/c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/$VSVER/$TOOLSVER/Common7/IDE/CommonExtensions/Microsoft/TestWindow
        - export PATH=$PATH:/c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/$VSVER/$TOOLSVER/MSBuild/Current/bin/Roslyn
        - export INCLUDE=/c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2017/$TOOLSVER/VC/Tools/MSVC/$MSVER/include
        - export INCLUDE=$INCLUDE:/c/Program\ Files\ \(x86\)/Windows\ Kits/10/Include/$WKITVER/ucrt
        - export INCLUDE=$INCLUDE:/c/Program\ Files\ \(x86\)/Windows\ Kits/10/include/$WKITVER/ucrt
        - export INCLUDE=$INCLUDE:/c/Program\ Files\ \(x86\)/Windows\ Kits/10/include/$WKITVER/shared
        - export INCLUDE=$INCLUDE:/c/Program\ Files\ \(x86\)/Windows\ Kits/10/include/$WKITVER/um
        - export INCLUDE=$INCLUDE:/c/Program\ Files\ \(x86\)/Windows\ Kits/10/include/$WKITVER/winrt
        - export INCLUDE=$INCLUDE:/c/Program\ Files\ \(x86\)/Windows\ Kits/10/include/$WKITVER/cppwinrt
        - export LIB=/c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/$VSVER/$TOOLSVER/VC/Tools/MSVC/$MSVER/ATLMFC/lib/x86
        - export LIB=/c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/$VSVER/$TOOLSVER/VC/Tools/MSVC/$MSVER/lib/x86:$LIB
        - export LIB=/c/Program\ Files\ \(x86\)/Windows\ Kits/10/lib/$WKITVER/ucrt/x86:$LIB
        - export LIB=/c/Program\ Files\ \(x86\)/Windows\ Kits/10/lib/$WKITVER/um/x86:$LIB
        # Build wxWidgets
        - wget -q https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.3/wxWidgets-3.1.3.tar.bz2
        - tar xf wxWidgets-3.1.3.tar.bz2 > NUL
        - cd wxWidgets-3.1.3/build/msw
        - nmake -C -f makefile.vc BUILD=release RUNTIME_LIBS=static UNICODE=1 DEBUG_INFO=0 DEBUG_FLAG=0
        - cd ../../..
        - WX_ROOT_HINT=-DwxWidgets_ROOT_DIR:PATH=$PWD/wxWidgets-3.1.3/
        - WX_LIB_HINT=-DwxWidgets_LIB_DIR:PATH=$PWD/wxWidgets-3.1.3/lib/vc_lib
        # Install VTK binaries
        - wget -q https://github.com/GollyGang/ready/releases/download/0.8/VTK-8.1.2_msvc14_x86_shared.7z
        - 7z x VTK-8.1.2_msvc14_x86_shared.7z
        - VTK_HINT=-DVTK_DIR=$PWD/VTK/lib/cmake/vtk-8.1
        # Specify where the output will appear
        - BIN_FOLDER=Release/
        # Allow the executables to load the shared VTK DLLs
        - export PATH=$PWD/VTK/bin:$PATH
    - os: linux
      name: Ubuntu_18.04_gtk3_vtk7_wx3.0.4_clang
      dist: bionic
      compiler: clang
      addons:
        apt:
          packages:
            - libvtk7-dev
            - ocl-icd-opencl-dev
            - libgtk-3-dev
            - libwxgtk3.0-gtk3-dev
            - libboost-program-options-dev
    - os: linux
      name: Ubuntu_18.04_gtk3_vtk7_wx3.0.4_gcc
      dist: bionic
      compiler: gcc
      addons:
        apt:
          packages:
            - libvtk7-dev
            - ocl-icd-opencl-dev
            - libgtk-3-dev
            - libwxgtk3.0-gtk3-dev
            - libboost-program-options-dev
    - os: linux
      name: Ubuntu_18.04_gtk2_vtk7_wx3.0.4_gcc
      dist: bionic
      compiler: gcc
      addons:
        apt:
          packages:
            - libvtk7-dev
            - ocl-icd-opencl-dev
            - libgtk2.0-dev
            - libwxgtk3.0-dev
            - libboost-program-options-dev
    # debugging build failures when both gtk2 and 3 were installed
    - os: linux
      name: Ubuntu_18.04_gtk2_gtk3_vtk7_wx3.0.4_gcc_DEBUG1_g2g3w2w3
      dist: bionic
      compiler: gcc
      addons:
        apt:
          packages:
            - libvtk7-dev
            - ocl-icd-opencl-dev
            - libgtk2.0-dev
            - libgtk-3-dev
            - libwxgtk3.0-dev
            - libwxgtk3.0-gtk3-dev
            - libboost-program-options-dev
    - os: linux
      name: Ubuntu_18.04_gtk2_gtk3_vtk7_wx3.0.4_gcc_DEBUG2_g2g3w2
      dist: bionic
      compiler: gcc
      addons:
        apt:
          packages:
            - libvtk7-dev
            - ocl-icd-opencl-dev
            - libgtk2.0-dev
            - libgtk-3-dev
            - libwxgtk3.0-dev
            - libboost-program-options-dev
    - os: linux
      name: Ubuntu_18.04_gtk2_gtk3_vtk7_wx3.0.4_gcc_DEBUG3_g2g3w3
      dist: bionic
      compiler: gcc
      addons:
        apt:
          packages:
            - libvtk7-dev
            - ocl-icd-opencl-dev
            - libgtk2.0-dev
            - libgtk-3-dev
            - libwxgtk3.0-gtk3-dev
            - libboost-program-options-dev
    # disabled vtk6 support pending a workaround for the vtkRenderingOpenGL(2) issue
    #- os: linux
    #  name: Ubuntu_16.04_gtk2_vtk6_wx3.0.2
    #  dist: xenial
    #  compiler: gcc
    #  addons:
    #    apt:
    #      packages:
    #        - libvtk6-dev
    #        - ocl-icd-opencl-dev
    #        - libgtk2.0-dev
    #        - libwxgtk3.0-dev
    #        - libboost-program-options-dev
    - os: osx
      osx_image: xcode11.3
      name: MacOS_10.14_xcode11.3_vtk8.2.0_wx3.0.4
      addons:
        homebrew:
          packages:
            - vtk
            - wxmac
            - boost
    - os: osx
      osx_image: xcode11.2
      name: MacOS_10.14_xcode11.2_vtk8.2.0_wx3.0.4
      addons:
        homebrew:
          packages:
            - vtk
            - wxmac
            - boost
    - os: osx
      name: MacOS_10.13_xcode9.4.1_vtk8.2.0_wx3.0.4
      addons:
        homebrew:
          update: true
          packages:
            - vtk
            - wxmac
            - boost

branches:
  only:
    - gh-pages

before_script:  
  - mkdir build
  - cd build
  - cmake $VTK_HINT $WX_ROOT_HINT $WX_LIB_HINT $OCL_INCLUDE $OCL_LIB $BOOST_ROOT -DCMAKE_BUILD_TYPE=Release ..

script:
  # Test that the code builds on this platform
  - cmake --build . --config Release
  # Test that rdy works on this platform
  - PATTERNS_FOLDER=$PWD
  - cd ./$BIN_FOLDER
  - if [ "$TRAVIS_OS_NAME" = "linux" ]||[ "$TRAVIS_OS_NAME" = "osx" ]; then ./rdy -i $PATTERNS_FOLDER/Patterns/CPU-only/grayscott_1D.vti -n 100 -o gs_100.vti -v; fi
  # (Currently on this Windows platform on Travis it fails to load some shared libraries, so this test is conditional.)
