language: cpp

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc
      addons:
        apt:
          packages:
            - libvtk6-dev
            - ocl-icd-opencl-dev
            - libgtk2.0-dev
            - libwxgtk3.0-dev
            - libboost-all-dev
    - os: osx
      before_install:
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install vtk wxmac boost
    - os: windows
      before_install:
        - choco install boost-msvc-12
        - mkdir WX
        - wget https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.1/wxWidgets-3.1.1-headers.7z
        - wget https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.1/wxMSW-3.1.1_vc140_Dev.7z
        - wget https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.1/wxMSW-3.1.1_vc140_ReleaseDLL.7z
        - 7z x -oWX -y wxWidgets-3.1.1-headers.7z
        - 7z x -oWX -y wxMSW-3.1.1_vc140_Dev.7z
        - 7z x -oWX -y wxMSW-3.1.1_vc140_ReleaseDLL.7z
        - WX_DIR=-DwxWidgets_ROOT_DIR=$PWD/WX
        - WX_LIB_DIR=-DwxWidgets_LIB_DIR=$PWD/WX/lib/vc140_dll
        - echo $WX_DIR
        - ls $WX_DIR
        - echo $WX_LIB_DIR
        - ls $WX_LIB_DIR
        - wget https://github.com/GollyGang/ready/releases/download/0.8/VTK-8.1.2_msvc14_x86_shared.7z
        - 7z x VTK-8.1.2_msvc14_x86_shared.7z
        - VTK_DIR=-DVTK_DIR=$PWD/VTK/lib/cmake/vtk-8.1

branches:
  only:
    - gh-pages

before_script:  
    - mkdir build
    - cd build
    - cmake $VTK_DIR $WX_DIR $WX_LIB_DIR ..

script: make 
