name: macOS

on:
  push:
    branches:
      - gh-pages
  pull_request:
    branches:
      - gh-pages

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15] # macos-11.0 (disabled since was queuing for long periods)
        build_type: [Debug, Release]
    runs-on: ${{ matrix.os }}

    steps:

    - name: git clone
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        brew install vtk wxmac
        echo "MACOS_QT5_HINT=$(brew --prefix qt5)" >> $GITHUB_ENV

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: |
        cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_PREFIX_PATH=${{ env.MACOS_QT5_HINT }}

    - name: Build
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --config ${{matrix.build_type}}

    - name: Test (with OpenCL)
      if: matrix.build_type == 'Release'
      # Run the full suite of tests since OpenCL is available
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: ctest -C ${{matrix.build_type}}

    - name: Test (without OpenCL)
      if: matrix.build_type == 'Debug'
      # Run a restricted suite of tests (OpenCL is available but the tests are slow on Debug)
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: ctest -R rdy -C ${{matrix.build_type}}
