name: Build

on: pull_request

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-16.04, macos-10.15, windows-2019] #ubuntu-20.04, ubuntu-18.04, macos-11.0, windows-2019, windows-2016]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies (for Windows)
      if: matrix.os == 'windows-2019'
      run: |
        C:\msys64\usr\bin\wget.exe -q https://github.com/GollyGang/ready/releases/download/0.8/VTK-8.1.2_msvc14_x86_shared.7z
        7z x VTK-8.1.2_msvc14_x86_shared.7z
        VTK_HINT=-DVTK_DIR=$PWD/VTK/lib/cmake/vtk-8.1

    - name: Install dependencies (for Ubuntu 20.04 and 18.04)
      if: matrix.os == 'ubuntu-20.04' || matrix.os == 'ubuntu-18.04'
      run: |
        sudo apt-get update
        sudo apt-get install libvtk7-dev ocl-icd-opencl-dev libgtk-3-dev libwxgtk3.0-gtk3-dev

    - name: Install dependencies (for Ubuntu 16.04)
      if: matrix.os == 'ubuntu-16.04'
      run: |
        sudo apt-get update
        sudo apt-get install libvtk6-dev ocl-icd-opencl-dev libgtk2.0-dev libwxgtk3.0-dev

    - name: Install dependencies (for macOS)
      if: matrix.os == 'macos-11.0' || matrix.os == 'macos-10.15'
      run: |
        brew install vtk wxmac
        echo "MACOS_QT5_HINT=$(brew --prefix qt5)" >> $GITHUB_ENV

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE $VTK_HINT -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_PREFIX_PATH=${{ env.MACOS_QT5_HINT }}

    - name: Build
      # Execute the build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Test (with OpenCL)
      if: matrix.os == 'macos-11.0' || matrix.os == 'macos-10.15'
      # Run the full suite of tests if OpenCL is available
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ctest -C $BUILD_TYPE

    - name: Test (without OpenCL)
      # Run a restricted suite of tests if OpenCL is not available
      if: matrix.os != 'macos-11.0' && matrix.os != 'macos-10.15'
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ctest -R rdy -C $BUILD_TYPE
